branchName: ${steps.Get_current_date.outputs.date}
defaultBranch: 'develop'
autoCloseIssue: true

branches:
  - label: feature
    prefix: feature/
  - label: hotfix
    prefix: hotfix/
  - label: release
    prefix: release/
