echo "::set-output name=date::$(date +'%Y%m%d')

branchName: '${%date}'
defaultBranch: 'develop'
autoCloseIssue: true

branches:
  - label: feature
    prefix: feature/
  - label: hotfix
    prefix: hotfix/
  - label: release
    prefix: release/
