branchName: ${date +"%G%m%e"}
defaultBranch: 'develop'
autoCloseIssue: true

branches:
  - label: feature
    prefix: feature/
  - label: hotfix
    prefix: hotfix/
  - label: release
    prefix: release/
